apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gzctf-helm.fullname" . }}
spec:
  accessModes:
    - {{ .Values.gzctf.pvc.accessMode }}
  resources:
    requests:
      storage: 2Gi
  storageClassName: {{ .Values.gzctf.pvc.storageClassName }}
