{{- if .Values.gzctf.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gzctf.serviceAccountName" . }}
  labels:
    {{- include "gzctf.labels" . | nindent 4 }}
  {{- with .Values.gzctf.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.gzctf.serviceAccount.automount }}
{{- end }}
