name: Release Charts

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'gzctf/**'

jobs:
  release:
    permissions:
      contents: write # for helm/chart-releaser-action to push chart release and create a release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0
          
      - name: Install Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4.3.1
        with:
          version: v3.10.1

      - name: Add dependency chart repos
        run: |
          helm repo add dandydeveloper https://dandydeveloper.github.io/charts/
          helm repo add minio https://charts.min.io/
          helm repo add bitnami https://charts.bitnami.com/bitnami/
          cd gzctf/
          helm dep up

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@cae68fefc6b5f367a0275617c9f83181ba54714f # v1.7.0
        with:
          config: "./.github/configs/cr.yaml"
          charts_dir: .
        env:
          CR_TOKEN: "${{ github.token }}"


